booknest/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'booknest.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^booksys/', include('booksys.urls', namespace='booksys')),
    url(r'^admin/', include(admin.site.urls)),
)

booksys/urls.py
from django.conf.urls import patterns, url
from booksys import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^(?P<book_id>\d+)/$', views.detail, name='detail'),
	url(r'^(?P<book_id>\d+)/results/$', views.results, name='results'),
)

booksys/models.py
from django.db import models

class Publisher(models.Model):
	name = models.CharField(max_length=255)
	address = models.CharField(max_length=255)
	contact_no = models.CharField(max_length=50)
	def __unicode__(self):
		return self.name

class Department(models.Model):
	name = models.CharField(max_length=255)
	contact_no = models.CharField(max_length=50)
	def __unicode__(self):
		return self.name

class Category(models.Model):
	acronym = models.CharField(max_length=10)
	description = models.CharField(max_length=255)
	def __unicode__(self):
		return self.acronym

class Author(models.Model):
	firstname = models.CharField(max_length=255)
	middlename = models.CharField(max_length=255)
	lastname = models.CharField(max_length=255)
	department = models.ForeignKey(Department)
	def __unicode__(self):
		return self.lastname + ', ' + self.firstname

class Book(models.Model):
	title = models.CharField(max_length=255)
	pub_date = models.DateTimeField('date published')
	author = models.ForeignKey(Author)
	publisher = models.ForeignKey(Publisher)
	category = models.ForeignKey(Category)
	def __unicode__(self):
		return self.title

booksys/views.py
from django.shortcuts import render, get_object_or_404
from django.template import RequestContext, loader
from booksys.models import Book

def index(request):
	latest_book_list = Book.objects.order_by('title')
	return render(request, 'booksys/index.html', {'latest_book_list': latest_book_list})

def detail(request, book_id):
	book = get_object_or_404(Book, pk=book_id)
	return render(request, 'booksys/detail.html', {'book': book})

def results(request, book_id):
	return HttpResponse("You're looking at the results of %s." % book_id)

booksys/templates/booksys/detail.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block title %}{{ book.title }}{% endblock %}

{% block branding %}
<h1 id="site-name">{% trans 'BookNest' %}</h1>
{% endblock %}

{% block content %}
<style type="text/css">
	table {
		width: 100%;
	}
	th {
		width: 40%;
	}
</style>
<h2>{{ book.title }}</h2>
<fieldset>
	<legend>Details</legend>
	<table>
		<tr>
			<th>Title</th>
			<td>{{ book.title }}</td>
		</tr>
		<tr>
			<th>Date of Publication</th>
			<td>{{ book.pub_date }}</td>
		</tr>
		<tr>
			<th>Author</th>
			<td>{{ book.author }}</td>
		</tr>
	</table>
</fieldset>
{% endblock %}

{% block nav-global %}{% endblock %}

booksys/templates/booksys/index.html
{% if latest_book_list %}
	<ul>
	{% for book in latest_book_list %}
		<li><a href="{% url 'booksys:detail' book.id %}">{{ book.title }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>No books are available.</p>
{% endif %}